services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redisdata:/data

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  gotenberg:
    image: gotenberg/gotenberg:8.24
    restart: unless-stopped
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*

  tika:
    image: apache/tika:latest
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    environment:
      TZ: ${TZ}

      PAPERLESS_REDIS: ${PAPERLESS_REDIS}
      PAPERLESS_DBHOST: ${PAPERLESS_DBHOST}
      PAPERLESS_DBNAME: ${PAPERLESS_DBNAME}
      PAPERLESS_DBUSER: ${PAPERLESS_DBUSER}
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS}

      PAPERLESS_TIKA_ENABLED: ${PAPERLESS_TIKA_ENABLED}
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: ${PAPERLESS_TIKA_GOTENBERG_ENDPOINT}
      PAPERLESS_TIKA_ENDPOINT: ${PAPERLESS_TIKA_ENDPOINT}

      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${PAPERLESS_CSRF_TRUSTED_ORIGINS}
      PAPERLESS_ALLOWED_HOSTS: ${PAPERLESS_ALLOWED_HOSTS}

    volumes:
      - paperless_data:/usr/src/paperless/data
      - paperless_media:/usr/src/paperless/media
      - paperless_consume:/usr/src/paperless/consume
      - paperless_export:/usr/src/paperless/export

  paperless-ai:
    image: clusterzx/paperless-ai:latest
    restart: unless-stopped
    depends_on:
      - paperless
    ports:
      - "8002:3000"

    volumes:
      - paperless_ai_data:/app/data

  paperless-gpt:
    image: icereed/paperless-gpt:latest
    restart: unless-stopped
    depends_on:
      - paperless
    ports:
      - "3002:8080"
    environment:
      LOG_LEVEL: ${LOG_LEVEL}

    volumes:
      - paperless_gpt_prompts:/app/prompts

  dozzle:
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dozzle_data:/data
    ports:
      - "8080:8080"

volumes:
  pgdata:
  redisdata:

  paperless_data:
  paperless_media:
  paperless_consume:
  paperless_export:

  paperless_ai_data:
  paperless_gpt_prompts:

  dozzle_data:
